baseURL = 'https://tokisuno.github.io'
languageCode = 'en-ca'
title = 'toki blog'
theme = "toki-xmin"

[params]
  footer="[youtube](https://youtube.com/tokisuno) | [goodreads](https://www.goodreads.com/user/show/146547946-tokisuno) [rss]|(https://tokisuno.rocks/index.xml)"
  [params.author]
    name="tokisuno"

[menu]
[[menu.main]]
  name='/home/'
  pageRef='/'
  weight=10
[[menu.main]]
  name='/about/'
  pageRef='aboutme'
  weight=20
[[menu.main]]
  name='/equipment/'
  pageRef='equip'
  weight=30
[outputs]
  home = ["html", "rss"]
  [outputFormats]
    [outputFormats.RSS]
      mediaType = "application/rss+xml"
      baseName="feed"

